### ISSUE TITLE
should not JSON.parse by default

### ISSUE THREAD

**Issue by blackbing** [thereactivestack/react-cookie#47]
https://github.com/eXon/react-cookie/blob/master/index.js#L42  

By default, it will execute `JSON.parse` to parse the value. the problem is here. for example.

```
JSON.parse('99999999999999999'); //-> 100000000000000000
JSON.parse('10209033848396525'); //-> 10209033848396524
```

it is confused when I just want to set a cookie but getting the wrong value. I think it should not execute `JSON.parse` by default. Or keep it simple and just leave this transform function to others.

**Comment by eXon** [comment]
The problem here is that javascript think it is a number but it is a string. A lot of people are having the same kind of problem.

I think having an automatic stringify / parse is still nice but it should be kept only on objects. The check can be as simple as if the cookie value is starting with a { or [, we're parsing it (unless it throws of course).

Would it solve your problem?

**Comment by blackbing** [comment]
Sounds good. Or you can just add a type check if 'cookieVar' is an object
or an array.

**Comment by eXon** [comment]
They are unfortunally saved in string only because it is how cookies work under the hood. Should be fixed :)
