### ISSUE TITLE
Cookie not generating with *.subdomain

### ISSUE THREAD

**Issue by carterwarrengravitas** [thereactivestack/react-cookie#59]
```
cookie.save('cookiename', JSON.stringify(data), {
        path: '/',
        expires: fortNightAway,
        domain: 'https://*.mydomain.com',
      })
```

My cookie is not being generated with the above code. fortNightAway is fine, the expiration is setting itself to the variable and the path is working well.

(Running on Chrome on a Mac, though I assume its a syntax issue.)

--- EDIT ------------------------------

```
cookie.save('cookiename', JSON.stringify(data), {
        path: '/',
        expires: fortNightAway,
      },
      {domain: 'https://*.mydomain.com'});
```

This code is now generating a cookie at least, but it isn't being passed on to the subdomain.

**Comment by carterwarrengravitas** [comment]
I am unable to set a domain using this plugin regardless of the syntax variations I try.

**Comment by eXon** [comment]
This is because the domain should not contain the protocol. It must be: `sub.mydomain.com`.

You can use `mydomain.com` or `.mydomain.com` (dot at the beginning) if you want them to be available on all subdomains.

(see http://stackoverflow.com/a/23086139/1692356)

I will make the doc more clear on that regard.

**Comment by eXon** [comment]
The doc had a wrong example. I get why you were using that syntax. It's fixed now.
