### ISSUE TITLE
Removing cookie not working in staging environment

### ISSUE THREAD

**Issue by amalv** [thereactivestack/react-cookie#65]
The thing is this works just fine in the local environment (`localhost:3000`) , however the exactly same code in the staging environment (`beta.dev.<domain>.com`) it does not delete the cookie, any idea what may be causing this?

The code is implemented in react, here is the action representing the user logout:

> .../app/actions/auth.js

```
export function logout() {
  return (dispatch, getState) => {
    const state = getState();
    const userToken = state.auth.user.token;

    userApi.logout(userToken);
    deleteUserAuthCookie();
    return dispatch(logoutSuccess());
  };
}
```

The `deleteUserAuthCookie` code (which uses the react-cookie library):

> .../app/utilities/auth.js

```
export const deleteUserAuthCookie = () => {
  const options = {
    path: '/',
  };
  Cookies.remove(USER_COOKIE_NAME, options);
};
```

**Comment by amalv** [comment]
I fixed this adding the domain to the `Cookies.remove` options, without the domain it worked for local environment but not for staging / production environments.

**Comment by yuinkerz** [comment]
@amalv May I ask how did you fix this issue?

**Comment by amalv** [comment]
@yuinkerz Is just as explained in my comment, I had to had the domain to `Cookies.remove` options (the path).

**Comment by oredavids** [comment]
I encountered a similar issue with cookies when the cookie name has the "__Secure-" prefix. The browser was blocking the set-header because the secure cookie option was not set. See: https://tools.ietf.org/html/draft-west-cookie-prefixes-05#section-3

<img width="419" alt="Screen Shot 2021-04-22 at 10 05 02 AM" src="https://user-images.githubusercontent.com/21035422/115747454-83dee200-a352-11eb-84ae-e69d565104d7.png">
